### ISSUE TITLE
Users can take notes anything as day wise

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#107]
![1325487c-f451-4604-91c4-e25124aafc2b](https://user-images.githubusercontent.com/74618071/155758619-543833cb-5303-4962-806c-9551a2e1cd05.jpg)

There will be a ``` Add Button ``` , and when user will click add button it will just input edit text on a dialogue box , and it will store the current date and the input notes in firebase database as below provided the ``` Green Colour ``` . 

![nodtess](https://user-images.githubusercontent.com/74618071/155758831-58fbe5fa-e936-4e60-a321-5d886314db82.png)

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC
