### ISSUE TITLE
Rank List working in App using Firebase

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#112]
Rank List working in App using Firebase

Node SS : 

![Tracky - Track the Goal – Firebase console - Google Chrome 27-02-2022 12 19 01 AM](https://user-images.githubusercontent.com/74618071/155855473-75647b66-03db-4d50-b72c-05b891d95e1b.png)

You need to add as per this .. [ Just contact me , I will discuss better }

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌️
