### ISSUE TITLE
Delete archive goal automatically after a particular time.

### ISSUE THREAD

**Issue by SB2318** [maityamit/Tracky-Track-your-goals-or-targets#118]
In the case of a mailing application, some mails are automatically deleted after a particular period. We can implement this feature in this application. I will try to work on this issue, But give me at least 4 days for this.

Assign it to me.

**Comment by maityamit** [comment]
@SB2318 
Give your time , 
But here I will say you that , 

``` There will be a settings that user can on or off , if user off the settings for particular goal then archive goal can't be delete any period of time , if user turn on settings then will this fn will execute ```

**Comment by SB2318** [comment]
Yeah, that will also be great. I will contact you before working on this.
