### ISSUE TITLE
Notes Recyclerview add on strike notes section 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#126]
![WhatsApp - Google Chrome 28-02-2022 9 55 53 AM](https://user-images.githubusercontent.com/74618071/155923933-6cca425b-2b2f-4afa-9da8-f5cd7e7dcc47.png)

![73291b15-ea0c-4865-a43e-5c140102172e](https://user-images.githubusercontent.com/74618071/155923941-a37f0c34-eb84-44fb-9924-3abe442f3f14.jpg)

**Comment by aritra-tech** [comment]
I would like to work on this issue under JWOC
