### ISSUE TITLE
Archive and Profile Section will create on Main Activity

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#13]
**You need to just create Archive and Profile Section will create on Main Activity as below image attached ..**

![Untitled – Figma - Google Chrome 30-01-2022 8 21 09 PM](https://user-images.githubusercontent.com/74618071/151704797-534330f4-3d8a-4d20-b756-9f0cb300cc50.png)

**Comment by pree-T** [comment]
May I work on this? Can someone guide me as I am new to open source contribution?

**Comment by maityamit** [comment]
@pree-T Absolutely , I am here for helping the community . 
I will defenetly guide you even if are beginner. But from 1st Feb when the coding phase will began .

**Comment by pree-T** [comment]
> @pree-T Absolutely , I am here for helping the community . I will defenetly guide you even if you are beginner. But from 1st Feb when the coding phase will began .

Thank you so much @maityamit !

**Comment by pree-T** [comment]
What do I need to do exactly as a fic to this issue? Can you guide me @maityamit

**Comment by maityamit** [comment]
@pree-T Yes , I will send a UI , Of that basically you need to implement that .. 

I will send an UI on Evening ..
