### ISSUE TITLE
When goal ( end date = current date +1 ) the goal will automatically go to archive section. 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#14]
1. There is an ```Archive Fragment`` 
2. Set up a Recycler View which will fetch the data from firebase
3. When any goal ( ```end_date == today_date+1``` ) It will copy the ```goal_name``` , ```consistency``` , ```goal_target_date``` in a local string and create a New Node under ```Users/user_id``` parent node that called ```Archived_Goal``` under that node you just create a ```key``` and store according the value and display in the ```Archive Fragment``` recycler view.

**Comment by raxvab** [comment]
I want to work with this issue under JWOC

**Comment by SB2318** [comment]
@maityamit ,I would like to work on this issue under JWOC. Please assign it to me.

**Comment by maityamit** [comment]
@SB2318 I have some discussion about this issue. 
Please ping on #tracky group on Discord on JWoC .

**Comment by SB2318** [comment]
Okay @maityamit , can I do it in the evening or after 5 pm?

**Comment by maityamit** [comment]
@SB2318 Absolutely No problem
