### ISSUE TITLE
Share APK file feature in Settings Tab

### ISSUE THREAD

**Issue by binayshaw7777** [maityamit/Tracky-Track-your-goals-or-targets#147]
Allow user to share App in the form of APK / or other means.

**Comment by maityamit** [comment]
@binayshaw7777 , yes
But I think there will be option share Link of the play store . 
We know Our App is not live .. 
So , there will be two option 
1. share apk
2. share link

as of now share link function will disable

**Comment by binayshaw7777** [comment]
Yes @maityamit  we can do that!

**Comment by maityamit** [comment]
@binayshaw7777 Carry on 👍
