### ISSUE TITLE
When user will demand for leave in the edit text it will only Numbers .. 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#149]
### Contact Details

maityamit308@gmail.com

### What happened?

When user will demand for leave in the edit text it will take only Numbers .. 
But now it takes string also and show error .. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC
