### ISSUE TITLE
[Bug]:  User can take break after Checkin

### ISSUE THREAD

**Issue by binayshaw7777** [maityamit/Tracky-Track-your-goals-or-targets#152]
### Contact Details

binayshaw7777@gmail.com

### What happened?

A bug happened! 
User can take break break even if he checks in.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@binayshaw7777 
I think it should be 
``` User can't take ```

**Comment by binayshaw7777** [comment]
@maityamit  I meant user can still take break after checking in, so this is the bug

**Comment by maityamit** [comment]
Ohk @binayshaw7777
