### ISSUE TITLE
Recreate the UI of the Add Goal Activity

### ISSUE THREAD

**Issue by aritra-tech** [maityamit/Tracky-Track-your-goals-or-targets#153]
### Feature description

Redesign the Add Goal Activity to make the UI more impressive.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@aritra-tech Have you any template ?

**Comment by aritra-tech** [comment]
No, I don't have. But have a idea for the UI

**Comment by maityamit** [comment]
Ohk , you can give any sample @aritra-tech

**Comment by aritra-tech** [comment]
Ok ok
