### ISSUE TITLE
Change this Logout Dialogue box to Material Dialogue box 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#156]
### Feature description

# Change It
![d016e008-bb38-414b-b872-12263cf19c8f](https://user-images.githubusercontent.com/74618071/156756901-71600135-20a1-434a-89d2-a1a52b36e6c3.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌
