### ISSUE TITLE
Forget Password not send to the user , show error 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#170]
### Contact Details

maityamit308@gmail.com

### What happened?

Forget Password not send to the user 

![dfe1f285-5df5-4d66-ba04-c24306cf1012](https://user-images.githubusercontent.com/74618071/156900107-2e8f947f-9b4d-43c5-a5f2-e15c5d334d2f.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritra-tech** [comment]
I would like to work on this issue under JWOC ✌
