### ISSUE TITLE
Profile Photo URI load the Activity but can't Upload on Firebase and also can't add any node on firebase on Registration Activity

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#171]
### Contact Details

maityamit308@gmail.com

### What happened?

Profile Photo URI load the Activity but can't Upload on Firebase and also can't add any node on firebase on Registration Activity. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GeekLord04** [comment]
I want to work on this issue under JWOC
