### ISSUE TITLE
Email verification Function Remove when user will sign up using Email ID system 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#172]
### Feature description

Email verification Function Remove when user will sign up using Email ID system 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by GeekLord04** [comment]
I want to work on this issue under JWOC
