### ISSUE TITLE
When Anyone return from Sleep screen or from background the processing bar can't stop 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#174]
### Contact Details

maityamit308@gmail.com

### What happened?

When Anyone return from Sleep screen or from background the processing bar can't stop 
![46f8c207-2e0b-4887-9e24-7204c35a6be0](https://user-images.githubusercontent.com/74618071/156900596-dd6f938b-4984-4267-a674-a9a5dfa18839.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌
