### ISSUE TITLE
When User will want try to delete the goal , there will be a edittext on material dialogue box which will take user email ID , and cross verify

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#175]
### Feature description

When User will want try the goal , there will be a edit text on dialogue box which will take user email ID , that match , if match with user email then goal will delete nor show error 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC
