### ISSUE TITLE
[Bug]: When User will update the goal Image it will update successfully but Progress bar can't dismiss even after image added

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#176]
### Contact Details

maityamit308@gmail.com

### What happened?

[Bug]: When User will update the goal Image it will update successfully but Progress bar can't dismiss even after image added
![32b97f35-f12c-4534-99be-475b92f2e2d5](https://user-images.githubusercontent.com/74618071/156900892-4cba93af-6bf5-4c0c-a3b9-7597537b0a53.jpg)
d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SB2318** [comment]
Assign it to me
