### ISSUE TITLE
Fix Edit Dialog Box in Profile Activity and optimize the code.

### ISSUE THREAD

**Issue by aritra-tech** [maityamit/Tracky-Track-your-goals-or-targets#183]
### Contact Details

aritrarick2002@gmail.com

### What happened?

In the Edit dialog box in Profile Activity when we are writing the name with spaces it's showing wrong input so we have to change it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
#178 This issue already listed and assigned someone 
You can check

**Comment by aritra-tech** [comment]
Ok ok I am closing this one then

**Comment by maityamit** [comment]
@aritra-tech ok.
