### ISSUE TITLE
Email/Password Sign in System of Firebase add

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#2]
There already exists Google Sign in System of the firebase in the apps. 
But there need a Email/Password system in app in the front activity.

**Comment by GeekLord04** [comment]
Hey @maityamit ,
I'm interested in contributing to this issue.

**Comment by maityamit** [comment]
@GeekLord04 Means by using Firebase backend you need to develope sign in and register option . 
I am always here to help you and share with you any learning resources. 
If you confirm then response , I will assign you the task .

**Comment by GeekLord04** [comment]
@maityamit Yeah I'm ready to go.

**Comment by GeekLord04** [comment]
Hey @maityamit may I know whether you'll be providing the UI or I'll design it myself?

**Comment by shubhankar-bt** [comment]
I want to contribute to this issue

**Comment by maityamit** [comment]
@GeekLord04 Your code merged
