### ISSUE TITLE
[Bug]: Goal Edit Fragment UI collapses 

### ISSUE THREAD

**Issue by binayshaw7777** [maityamit/Tracky-Track-your-goals-or-targets#200]
### Contact Details

binayshaw7777@gmail.com

### What happened?

A bug happened! UI of Edit Goal Collapses in screen
![image](https://user-images.githubusercontent.com/62587060/156938298-4b63a8d0-948e-43f8-9f34-b546aa0c9faf.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@binayshaw7777 Hmm understand this is really good point 
Here we need improve
