### ISSUE TITLE
Feature: User details will show when clicked on any user

### ISSUE THREAD

**Issue by aritra-tech** [maityamit/Tracky-Track-your-goals-or-targets#230]
### Feature description

On clicking on any of the users in the Ranked Acivity it will show his name and profile in a material dialog box.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by aritra-tech** [comment]
Assign it to @binayshaw7777

**Comment by aritra-tech** [comment]
He is doing RR for the point

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC
