### ISSUE TITLE
[Bug]: Click on Reset button there will a confirmation material dialogue box 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#231]
### Contact Details

maityamit308@gmail.com

### What happened?

A bug happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritra-tech** [comment]
Assign me

**Comment by GeekLord04** [comment]
I want to contribute to this issue under JWOC
