### ISSUE TITLE
[Bug]:  Auto delete of any archive goal , depend upon settings 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#236]
### Contact Details

maityamit308@gmail.com

### What happened?

A bug happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@ken1000minus7 You can do this

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌️

**Comment by maityamit** [comment]
@ken1000minus7 
Listen , When user will turn on the auto delete button on archive target , then the goal will delete after 7 days .. after turn on 
If you need any clear approach , the you can contact me

**Comment by ken1000minus7** [comment]
Oki 👍, and after that if we turn off auto delete then it will not be deleted right?
