### ISSUE TITLE
[Bug]: Phone No Verification not working

### ISSUE THREAD

**Issue by aritra-tech** [maityamit/Tracky-Track-your-goals-or-targets#239]
### Contact Details

aritrarick2002@gmail.com

### What happened?

OTP is not coming.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@aritra-tech No it is working fine 
There was some simple one error.

**Comment by aritra-tech** [comment]
> @aritra-tech No it is working fine There was some simple one error.

Ok
