### ISSUE TITLE
[Bug]: A black screen occurs after Splash Screen and change the splash screen animation 

### ISSUE THREAD

**Issue by aritra-tech** [maityamit/Tracky-Track-your-goals-or-targets#255]
### Contact Details

aritrarick2002@gmail.com

### What happened?

After Splash screen a black screen comes then the Register Screen opens. And change the logo of Spash Screen , because is not similar to the logo of the app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@aritra-tech 
Everything ok , don't need to Change .. 
**Just Change the Splash Screen Logo , give app logo**

**Comment by aritra-tech** [comment]
There is a black screen coming after Splash Screen in my phone , ok I will change the logo .
