### ISSUE TITLE
Improve the search bar

### ISSUE THREAD

**Issue by GeekLord04** [maityamit/Tracky-Track-your-goals-or-targets#256]
### Contact Details

chiragofficial04@gmail.com

### What happened?

Will improve the search bar UI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@GeekLord04 
What do you want to do ? 
Any example

**Comment by GeekLord04** [comment]
@maityamit Will add neomorphism and decrease the rounded corners
