### ISSUE TITLE
Feature: Add simple Animation suitable for the app

### ISSUE THREAD

**Issue by aritra-tech** [maityamit/Tracky-Track-your-goals-or-targets#258]
### Feature description

Add some simple animations which will be better for the app.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@aritra-tech where do you want to add more animations?

**Comment by aritra-tech** [comment]
In all activities there will be simple animations

**Comment by maityamit** [comment]
@aritra-tech any example
