### ISSUE TITLE
Feature: Optimize the code  

### ISSUE THREAD

**Issue by aritra-tech** [maityamit/Tracky-Track-your-goals-or-targets#266]
### Feature description

Optimize the code.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@aritra-tech Sorry this not possible now .. 
Thanks for being an active participant of this project
