### ISSUE TITLE
User Profile Image Upload and Retrieve in Firebase Storage

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#28]
Your Work on : ```ProfileActivity.java```

Your Task : When User Press the  User Image View , It will open gallery of the Mobile phone and we can select a Image from the gallery . 
After select the Image will upload on the Firebase Storage and Create a Node called ```user_image``` under ```Users``` Parent node and it store the Image URL . And In the Profile Image view on ```ProfileActivity.java``` It will show , that retrieve from Firebase Backend. 

Help : 

1.  https://www.geeksforgeeks.org/android-how-to-upload-an-image-on-firebase-storage/
2. https://firebase.google.com/docs/storage/android/upload-files
3. https://firebase.google.com/docs/database

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC. 👌
