### ISSUE TITLE
Sign in - Sign up - Forgot Password UI design in XML File ( figma design Provided below ) 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#29]
You need to design ```Sign in``` - ```Sign up```  - ```Forgot password ``` UI in XML File .
<br>

Figma Link :  https://www.figma.com/file/L1InCSu9yHgv7J1BuAYugE/tracky?node-id=0%3A1

**Comment by binayshaw7777** [comment]
Hey I would I like to do design it under JWOC.

**Comment by binayshaw7777** [comment]
Hey @maityamit are we allowed to show our creativity or shall I design according to the provided design

**Comment by maityamit** [comment]
@binayshaw7777 
I give some , UI on ```figma``` . 
You can see or if you interest about to show your creativity then I will suggest you to give your ```Email ID``` , I will allow you to edit the Design on Figma . 
At first I will approve the Figma Design then you can implement it on the Android Studio. 

you Can design on Figma , Just drop your Email ID.

**Comment by binayshaw7777** [comment]
Sure, here it is binayshaw7777@gmail.com

**Comment by maityamit** [comment]
@binayshaw7777 I gave access 
You can now work only on that means Sign-In , Sign-Up , Forgot
