### ISSUE TITLE
Alert dialog box show 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#3]
When users basically press the logout button on Main Activity , they directly logout from app , but it will be very good if there exists one alert dialog box , when users click on logout button. 
Basically , it shows are you sure want to exist or not ?

**Comment by afreenabegum** [comment]
Hey @maityamit , I am interested in contributing to this issue.
But can you explain do we need to write the code and submit it.

Thanks
Afreena.

**Comment by maityamit** [comment]
@afreenabegum Yes , I hope you know the basics about the git and github , how to contribute . 
So , as per Please fork this project and change means create a alert dialog box at when users will click the logout button . 
Thats the task . 

I mentioned that where you need to add : https://github.com/maityamit/Tracky-Track-your-goals-or-targets/blob/master/app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java#L73

In this line you need a Alert Dialog box . 
If you want to do this please comment , I will assign you this task. 
And I am always here for help. 

Amit Maity
Thanks.

**Comment by afreenabegum** [comment]
Please assign it to me. I'll work on this.
I'll ping you if I needed help.

Thank you.

> @afreenabegum Yes , I hope you know the basics about the git and github , how to contribute . So , as per Please fork this project and change means create a alert dialog box at when users will click the logout button . Thats the task .
> 
> I mentioned that where you need to add : https://github.com/maityamit/Tracky-Track-your-goals-or-targets/blob/master/app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java#L73
> 
> In this line you need a Alert Dialog box . If you want to do this please comment , I will assign you this task. And I am always here for help.
> 
> Amit Maity Thanks.

**Comment by shubhanshu-coder** [comment]
i would like to work on it ?

**Comment by SaarthakMaini** [comment]
Hello! I would like to work on this. Can you please assign it to me?

**Comment by maityamit** [comment]
> Hello! I would like to work on this. Can you please assign it to me? 

Sorry @SaarthakMaini . As per first cum first serve basis , this issue already assigned to someone , you can choose another issue , which I will today / tommorow .

**Comment by SaarthakMaini** [comment]
Okay, thank you!!

**Comment by maityamit** [comment]
@afreenabegum 
Thanks for contribute ..

**Comment by afreenabegum** [comment]
> @afreenabegum Thanks for contribute ..

Thank you so much  for guiding me.
