### ISSUE TITLE
Add New Goal Activity UI design in XML File ( figma design Provided below )

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#31]
You need to design ```Add New Goal Activity``` UI in XML File .

Figma Link : https://www.figma.com/file/L1InCSu9yHgv7J1BuAYugE/tracky?node-id=0%3A1

**Comment by shubhankar-bt** [comment]
Hey i want to work on this issue under jwoc

**Comment by DurveshKumarPal** [comment]
Hey, I want to work on this issue under jwoc

**Comment by maityamit** [comment]
@DurveshKumarPal 
You can see that this is issue is assigned. 
On Sunday I will share lots of new issue fro next week .. 
Be ready to grab them

**Comment by DurveshKumarPal** [comment]
@maityamit I only need to change design blue to green?
