### ISSUE TITLE
Some Minor Small issues (05 minor issue ) 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#38]
- [x]  ``` Sign Up Activity``` : When User check the check box then Sign Up Button will work , neither it will not work .
- [x]  ``` Login Activity ```: App logo is not square , make it square
- [ ] ``` Current Fragment ``` : When user check in there show a Simple Alert Dialog Box to show confirm ya not But need material alert dialog box . 
- [ ]  ```Profile Activity ``` : When user check in there show a Simple Alert Dialog Box to show confirm ya not But need material alert dialog box . 
- [x]  When User Press on Back Button On ``` Home Activity ``` there will show a Confirm Material Dialog that : are you sure want to exit or not ? 

 Material Alert Dialog box Take Help from : [https://github.com/material-components/material-components-android/blob/master/docs/components/Dialog.md](url)

**Comment by binayshaw7777** [comment]
I want to work under JWOC

**Comment by aritra-tech** [comment]
I want to work on this issue under JWOC
