### ISSUE TITLE
On Main Activity when 1day remain , it shows "1 days" , but it will be "1 day"

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#4]
On Main Activity when 1day remain , it shows "1 days" , but it will be "1 day"

**Comment by Poulami2515** [comment]
I would like to contribute on this issue

**Comment by shubhanshu-coder** [comment]
i would like to work on it ?

**Comment by shubhanshu-coder** [comment]
i would like to work on it ?

**Comment by raxvab** [comment]
I want to work with this issue under JWOC

**Comment by maityamit** [comment]
@raxvab this already assigned

**Comment by maityamit** [comment]
@Poulami2515 
Thanks , Your code merged
