### ISSUE TITLE
Current Goal Search Function by name ,  Implement on Home Activity to search any existing goal 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#41]
Current Goal Search Function by name ,  Implement on ``` Home Activity ``` to search any existing goal 

[ Please contact on Discord with me before implement this ]

https://stackoverflow.com/questions/53991868/search-in-recyclerview-with-edittext

https://codinginflow.com/tutorials/android/recyclerview-edittext-search

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌️
