### ISSUE TITLE
Add a alarm functionality that users can select a alarm on particular time

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#42]
``` Dash Board Activity ``` : Add a alarm functionality that users can select a alarm on particular time for this goal  ( Create a Floating Alarm add button on ``` DashBoardACtivity ``` ) 

https://stackoverflow.com/questions/4459058/alarm-manager-example

[ Please contact on Discord with me before implement this ]

**Comment by binayshaw7777** [comment]
I want to work in the issue under JWOC
