### ISSUE TITLE
Share Text and Image through Intent to another App

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#43]
``` Dash Board Activity ``` : When User click on share button it will automatically take a screen shot and share option show. But You need to implement that : With Image A string will pass : That String will be : ``` [ Hi , I am {username} using this Tracky : Track your goal Application . and by using this I measured my { goal name } goal and be happy that I keep my consistency as { consistency percentage } %ge . And I have also completed my goal { goal_end_%ge} . be happy to share with you . #tracky #track #goal ```

https://stackoverflow.com/questions/20333186/how-to-share-image-text-together-using-action-send-in-android

[ Please contact on Discord with me before implement this ]

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC

**Comment by GeekLord04** [comment]
I want to work on this issue under JWOC
