### ISSUE TITLE
Dashboard Activity redesign in XML 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#48]
Figma : https://www.figma.com/file/L1InCSu9yHgv7J1BuAYugE/tracky?node-id=0%3A1

![tracky – Figma - Google Chrome 08-02-2022 10 28 10 AM](https://user-images.githubusercontent.com/74618071/152921134-84835cb0-b66b-4e98-9f8e-d145881a8aff.png)

**Comment by shubhankar-bt** [comment]
Assign me

**Comment by maityamit** [comment]
@shubhankar-bt 
I updated the design above . 
plzz check again. and if you faced any problem the you can discuss with me

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC

**Comment by shubhankar-bt** [comment]
I am already assigned

**Comment by binayshaw7777** [comment]
> 

It's easy level issue and it's been already more than 5 days.
