### ISSUE TITLE
There will be a confirmation alert when we check-in

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#6]
When we basically check in any goal any day , when we press check box it easily done .
But by mistake any users can press the check box. so we need a confirmation dialog box when users click on the check box that are you sure want to check in or not ?

**Comment by binayshaw7777** [comment]
Hey @maityamit ,
I'm really interested to add this feature to your project. I want to contribute.

**Comment by binayshaw7777** [comment]
Hey @maityamit  can you assign me this task?

**Comment by maityamit** [comment]
Absolutely , @binayshaw7777 
I will definitely assign , you 
But , please start doing Contribute after when the coding phase will start , that will be 1st Feb . 
Now , I will assign you. 
But , After 1 st Feb your contribute will measure.

**Comment by binayshaw7777** [comment]
Sure @maityamit  
I got it.

**Comment by shubhankar-bt** [comment]
Hey, I want to work on this feature in your app

**Comment by maityamit** [comment]
@shubhankar-bt 
Nice to see that , 
When coding phase will start , I will add more issues .. then You can choose between them . 
This particular issue is already assigned. 
Do not worry , Today Night I will add lots of issue basic , medium , hard level .
You can choose ..... 

Thanks
Amit Maity

**Comment by shubhankar-bt** [comment]
Hey, I want to work on this feature in your app

**Comment by maityamit** [comment]
@shubhankar-bt 
Hi , this issue already assigned as first cum first serve basis . 
You can do this issue #5 
It is now available

**Comment by maityamit** [comment]
@binayshaw7777 
Thanks . Your code merged on main directory ..
