### ISSUE TITLE
Highlight the Multiple dates , in which date user check-in the goal. ( Design is available on figma ) 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#62]
Highlight the Multiple dates , in which date user check-in the goal. ( Design is available on figma ) 

``` After the issue no #48 , you can start this work , hope within 1/2 days that issue will fix ```

Figma : https://www.figma.com/file/L1InCSu9yHgv7J1BuAYugE/tracky?node-id=138%3A2

help from : 

https://stackoverflow.com/questions/47450529/how-to-highlight-multiple-dates-in-a-android-calendarview-programmatically

https://github.com/SpongeBobSun/mCalendarView

**Comment by maityamit** [comment]
@SB2318 
Basically as I mentioned that after #48 issue completed , you can start your work . so after that I will contact with you. 
basically we need 1/2 days. 

So , just wait 1/2 days.

**Comment by SB2318** [comment]
Okay, I will contact you before starting the work.
