### ISSUE TITLE
Create a PDF of Active Goal from SQLITE DB , which will be create from Firebase Realtime DB Active Goal

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#63]
``` Create a PDF of Active Goal from SQLITE DB , which will be create from Firebase Realtime DB Active Goal ```

``` PDF Exported button will be on Profile Activity ``` 

Help : 

https://www.youtube.com/watch?v=uqyY7jM2cZI

https://stackoverflow.com/questions/34296149/creating-a-pdf-file-in-android-programmatically-and-writing-in-it/34296596#34296596

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC
