### ISSUE TITLE
Goal Image user can upload as Profile Image ( on Dashboard Activity ) 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#65]
Goal Image user can upload as Profile Image ( on Dashboard Activity ) 

``` After the issue no #48 , you can start this work , hope within 1/2 days that issue will fix. ```

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC

**Comment by GeekLord04** [comment]
I want to work on this issue under JWOC
