### ISSUE TITLE
At Dashboard Activity on Goal end time countdown , textview and background colour will change according to Timeline

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#66]
At Dashboard Activity on Goal end time countdown , textview and background colour will change according to Timeline

``` days left <= 33% ``` -> Red and Light red 
``` days left <= 66% ``` -> Yellow and Light Yellow
``` days left <= 100% ``` -> Green and Light green

**Comment by atishay5203** [comment]
hi , I want to work on this issue under JWOC
