### ISSUE TITLE
Delete Goal / Target

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#69]
Delete Goal / Target 

On ``` Dashboard Activity ``` when user will click on the delete icon on the top , then it will show a material alert dialogue box that show : 

``` Are you sure to delete this  ? ```  if user press yes then it will take a again user email id as input in a alert dialogue box if email id match then the goal/target will be deleted.

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌️
