### ISSUE TITLE
There will be a profile activity in this app 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#7]
There will be a profile activity in this app  where users can see their profile and logout option also available there.

I have already a design , but at first you pitch a design means profile activity.

**Comment by aritra-tech** [comment]
Hey @maityamit, I am interested in contributing to this issue.

Thanks
Aritra

**Comment by maityamit** [comment]
Yes , absolutely appreciating you  .. @aritra-tech 
I will send a basic design which you need to implement , also you can do extra on that things but basic design I will send today night. 
You can implement . and I will send all the description where to implement at today night.

Amit Maity.

**Comment by aritra-tech** [comment]
Ok @maityamit got it 👍

**Comment by aritra-tech** [comment]
Can you send the design @maityamit, it will be helpful.

**Comment by maityamit** [comment]
> Can you send the design @maityamit, it will be helpful.

Yes , @aritra-tech , I note it your , response , at night I will send you . Coding phase will start 1st Feb , after that you will start doing , today night। , i will just send you the Design. 
Basically it will be very simple design , till I will send you . 

Thanks

**Comment by aritra-tech** [comment]
Ok, thanks @maityamit

**Comment by maityamit** [comment]
@aritra-tech 

Your Task of this issue : 

- [ ]  Create a Activity Name : Profile Activity
- [ ]  Implement the following Layout ( I attached )
- [ ]  In the Firebase Realtime Database there will be already exist Username and Email Id Child. You need to retrieve the User Name and Email ID from the firebase to this activity.   
- [ ]  ** Note it , You do not need to do anything about Profile Image . There will be a new issue section only for profile image setup , there you or anyone cam do . 
- [ ]  ** Also you do not need to work on the Edit Button on the email and user name section . also they will have separate issue section . 
- [ ]  Implement Log Out Button .  


**Profile Activity Design :** 

![Frame 1](https://user-images.githubusercontent.com/74618071/151692793-a0529cfd-9650-4a00-9a77-e790bce0b4ce.png)


**Firebase Realtime 
![Tracky - Track the Goal – Firebase console - Google Chrome 30-01-2022 2 13 33 PM](https://user-images.githubusercontent.com/74618071/151692909-4d72c01e-dad7-4662-ba95-73bfe75f3deb.png)
Data Base Structure :** 


Thanks , If you faced any problem then contact ..
I am always there for help the community.

**Comment by aritra-tech** [comment]
From which Firebase do we have to retrieve the details, shall we create our own firebase project, or are you going to provide reference firebase project details?

**Comment by maityamit** [comment]
> I understood the task but I have some doubt that from which Firebase do we have to retrieve the details, shall we create our own firebase project, or are you going to provide reference firebase project details?

You need to create a just firebase project at your account ( I mentioned the process in discord server , once I will tag you ) , after creating, when you will log in the app the user name and Email ID will be stored and structure will automatically create in your firebase project .

**Comment by aritra-tech** [comment]
Ok ok got it

**Comment by shubhankar-bt** [comment]
Hey, I want to contribute to this issue

**Comment by maityamit** [comment]
@shubhankar-bt  yes , note it 
soon I will contact with new issue when coding phase will began.

**Comment by shubhankar-bt** [comment]
I am interested to contribute in this issue JWOC
