### ISSUE TITLE
Alarm Activity Re-design using Figma design I provided 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#71]
Alarm Activity Re-design using Figma 

Link : https://www.figma.com/file/L1InCSu9yHgv7J1BuAYugE/tracky?node-id=165%3A2

![Alarm Activity](https://user-images.githubusercontent.com/74618071/154414402-7868a7bc-317d-47f9-b439-688bdf2dc634.png)

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌️
