### ISSUE TITLE
Add floating button will be small in size , it will show only  add logo 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#73]
Add floating button will be small in size , it will show only  ``` add ``` logo .

Like : 

![7e208a96-3afc-4337-b313-667f2b42c145](https://user-images.githubusercontent.com/74618071/154491874-2b5aac06-c553-4387-b5bd-bdfe7c403109.jpg)

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC
