### ISSUE TITLE
Users not allow invalid goal create

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#8]
There is a particular activity where users can create a goal or target by using goal/target name , category and targeted date. 
But there users can create a goal with past date. but you need to write a logic that any users can not create a past date goal target. this will be invalid and not be created.

**Comment by binayshaw7777** [comment]
Hi I'm interested to do this! @maityamit

**Comment by shubhankar-bt** [comment]
Hi, I am interested in this issue.

**Comment by shubhankar-bt** [comment]
Hey, will you provide me a chance to work on this issue? @maityamit

**Comment by shubhankar-bt** [comment]
I am interested to contribute in this issue JWOC

**Comment by maityamit** [comment]
@binayshaw7777 Your code merged
