### ISSUE TITLE
Dashboard Activity some re-structured and retrieve some extra data from firebase 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#88]
Dashboard Activity some re-structured and retrieve some extra data from firebase 

Link : https://www.figma.com/file/L1InCSu9yHgv7J1BuAYugE/tracky?node-id=138%3A2

![tracky – Figma - Google Chrome 21-02-2022 6 35 42 PM](https://user-images.githubusercontent.com/74618071/154962008-7fa9efb2-f47f-42dd-9f42-22aa39e64cff.png)

**Comment by SB2318** [comment]
I want to work on this issue under JWOC.

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC
