### ISSUE TITLE
Settings Fragment Make and add some function

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#90]
Settings Fragment Make 

There already available settings fragments , you just to re-design the settings fragments which I provided here . 

Link : https://www.figma.com/file/L1InCSu9yHgv7J1BuAYugE/tracky?node-id=217%3A54

![tracky – Figma - Google Chrome 21-02-2022 6 35 56 PM](https://user-images.githubusercontent.com/74618071/154961791-b5b8644d-d3d3-4573-a52b-871556c3b51b.png)

**Comment by aritra-tech** [comment]
I want to work on this issue under JWOC
