### ISSUE TITLE
Take any user's best consistency goal and store firebase realtime db

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#93]
Take any user's best consistency goal and store firebase real-time db. 

![Tracky - Track the Goal – Firebase console - Google Chrome 23-02-2022 12 15 07 AM](https://user-images.githubusercontent.com/74618071/155198402-c364dba5-f279-4ee1-9b9f-abe9bc75a9dd.png)

From here you need to take the goal name and consistency of every user ( which goal consistency is high , that will be taken ) .

Then add on firebase 

![Untitled](https://user-images.githubusercontent.com/74618071/155198754-eebc3b8d-0f26-40f6-b4f5-9c3b23cd234c.png)
in this structure ..

**Comment by GeekLord04** [comment]
I want to work on this issue under JWOC

**Comment by maityamit** [comment]
@GeekLord04  within how many days , you will finish approx time ?

**Comment by GeekLord04** [comment]
Might complete it within 5-6 days. My last issue is almost complete

**Comment by maityamit** [comment]
ohk
