### ISSUE TITLE
Create a progress bar like that and set progress as completed goal percentage 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#94]
Create a progress bar like that and set progress as completed goal percentage 

![469d88dd-cec1-48d2-b3be-041e9e0e26cb (1)](https://user-images.githubusercontent.com/74618071/155207567-b8eb417d-e5df-4423-865e-f26ebf668dae.jpg)

Help Link : https://stackoverflow.com/questions/5745814/how-to-change-progressbars-progress-indicator-color-in-android

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌
