### ISSUE TITLE
Create a progress bar like that and set progress as goal consistency percentage on  Archive Activity

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#95]
Create a progress bar like that and set progress as goal consistency percentage on ```  Archive Activity ``` 

![469d88dd-cec1-48d2-b3be-041e9e0e26cb (1)](https://user-images.githubusercontent.com/74618071/155208794-495c5c1c-459e-4c8b-b16d-3b92b56db528.jpg)

Help Link : https://stackoverflow.com/questions/5745814/how-to-change-progressbars-progress-indicator-color-in-android

**Comment by aritra-tech** [comment]
I want to work on issues under JWOC

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌
