### ISSUE TITLE
Retrieve  Goal Image into CurrentGoal Frag Recyclerview items .. 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#97]
Retrieve  Goal Image into CurrentGoal Frag Recyclerview items .. 

![Tracky - Track the Goal – Firebase console - Google Chrome 23-02-2022 2 33 53 AM](https://user-images.githubusercontent.com/74618071/155219036-5c80fc9b-e4a5-45be-b144-0f1b80231a02.png)

![01587609-22f5-433f-89e0-00b6e7a57dc2 (1)](https://user-images.githubusercontent.com/74618071/155219159-6067905e-8867-4de9-9c19-7b0ba5712ac5.jpg)

**Comment by aritra-tech** [comment]
I want to work on issues under JWOC
