### ISSUE TITLE
When user will click on Show_Log Button on Settings frag it will retrieve Activity Nodes and show in a Dialogue box 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#99]
When user will click on Show_Log Button on Settings frag it will retrieve Activity Nodes and show in a Dialogue box 

![b68715f7-2e1c-469a-8805-f5978c45a570](https://user-images.githubusercontent.com/74618071/155494988-d4778491-0ec9-43fc-bda9-fc78fe5b98f9.jpg)

Nodes 👍 

![Tracky - Track the Goal – Firebase console - Google Chrome 24-02-2022 2 47 49 PM](https://user-images.githubusercontent.com/74618071/155495144-865f142e-41c4-4b38-9b5b-397bf5dd69fb.png)

Help Link :  https://www.google.com/search?q=listview+in+dialogue+box+android+studio&oq=listview+in+dialogue+box+android+studio&aqs=chrome..69i57j33i22i29i30.9084j0j7&sourceid=chrome&ie=UTF-8

**Comment by aritra-tech** [comment]
I want to work on issues under JWOC
